[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Wildcard
[[redirects]]
  from = "/*"
  to = "/au/:splat"
  status = 302
  conditions = { Country = ["AU"], }

# Wildcard
[[redirects]]
  from = "/*"
  to = "/us/:splat"
  status = 302
  conditions = { Country = ["US"], }

# Go to a direct file
[[redirects]]
  from = "/marketing-page"
  to = "/marketing-page-dk"
  status = 302
  conditions = { Country = ["DK"], }
