
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Go to a specific locale
[[redirects]]
  from = "/us/*"
  to = "/us/:splat"
  status = 200

[[redirects]]
  from = "/in/*"
  to = "/in/:splat"
  status = 200

[[redirects]]
  from = "/au/*"
  to = "/au/:splat"
  status = 200
# - - - - - - - - - - - - - - - - - - - -

# Wildcard
[[redirects]]
  from = "/*"
  to = "/au/:splat"
  status = 302
  conditions = { Country = ["AU"], }

# Wildcard
[[redirects]]
  from = "/*"
  to = "/us/:splat"
  status = 302
  conditions = { Country = ["US"], }

[[redirects]]
  from = "/*"
  to = "/in/:splat"
  status = 302
  conditions = { Country = ["IN"], }

# Go to a direct file
[[redirects]]
  from = "/marketing-page"
  to = "/marketing-page-dk"
  status = 302
  conditions = { Country = ["DK"], }
