# Go to a direct file
[[redirects]]
  from = "/marketing-page"
  to = "/au/marketing-page"
  status = 302
  conditions = { Country = ["AU"], }

[[redirects]]
  from = "/marketing-page"
  to = "/dk/marketing-page"
  status = 302
  conditions = { Country = ["DK"], }

[[redirects]]
  from = "/marketing-page"
  to = "/in/marketing-page"
  status = 302
  conditions = { Country = ["IN"], }

[[redirects]]
  from = "/marketing-page"
  to = "/us/marketing-page"
  status = 302
  conditions = { Country = ["US"], }


# - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Wildcard
#
# [[redirects]]
#   from = "/_next/*"
#   to = "/_next/:splat"
#   status = 200

# [[redirects]]
#   from = "/us/*"
#   to = "/us/:splat"
#   status = 200

# [[redirects]]
#   from = "/*"
#   to = "/au/:splat"
#   status = 302
#   conditions = { Country = ["AU"], }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - -