import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { CarouselContainer } from "../components/Carousel";
import { useState } from "react";
import Cookies from "js-cookie";

export default function Home({ header }) {
  const [headerText, setHeaderText] = useState(header);
  const [avatarColor, setAvatarColor] = useState("");

  const handleSavePreferences = (e) => {
    Cookies.set("personalGreeting", headerText);
    Cookies.set("avatar", avatarColor);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Netlify personalization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 id="header">{header}</h1>

      <p>current header: {headerText}</p>
      <p>current avartar color: {avatarColor}</p>

      <div>
        <form>
          <input
            type="text"
            id="headerText"
            onChange={(e) => setHeaderText(e.target.value)}
          />
          <div>
            <input
              type="radio"
              name="avatar"
              id="color1"
              value="aquamarine"
              onChange={(e) => setAvatarColor(e.target.value)}
            />
            <label htmlFor="color1">aquamarine</label>
          </div>
          <div>
            <input
              type="radio"
              name="avatar"
              id="color2"
              value="firebrick"
              onChange={(e) => setAvatarColor(e.target.value)}
            />
            <label htmlFor="color2">firebrick</label>
          </div>
          <div>
            <input
              type="radio"
              name="avatar"
              id="color3"
              value="cornsilk"
              onChange={(e) => setAvatarColor(e.target.value)}
            />
            <label htmlFor="color3">cornsilk</label>
          </div>
          <div>
            <input
              type="radio"
              name="avatar"
              id="color4"
              value="lavender"
              onChange={(e) => setAvatarColor(e.target.value)}
            />
            <label htmlFor="color4">lavender</label>
          </div>
          <div>
            <input
              type="radio"
              name="avatar"
              id="color5"
              value="tomato"
              onChange={(e) => setAvatarColor(e.target.value)}
            />
            <label htmlFor="color5">tomato</label>
          </div>
        </form>
        <button type="submit" onClick={handleSavePreferences}>
          Set preferences
        </button>
      </div>
      <CarouselContainer />
    </div>
  );
}

export const getStaticProps = (context) => {
  return {
    props: {
      header: "default from getStaticProps",
    },
  };
};
